import { CurrentUser } from '@/types/auth';

export const DEMO_USERS: Record<string, CurrentUser> = {
  super_admin: {
    userId: 'demo-super-admin-id',
    username: 'super_admin',
    email: 'admin@aums.edu',
    firstName: 'System',
    lastName: 'Admin',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['SUPER_ADMIN'],
    permissions: [
      'users.read',
      'roles.read',
      'permissions.read',
      'students.read',
      'faculty.read',
      'courses.read',
      'departments.read',
    ],
  },
  faculty: {
    userId: 'demo-faculty-id',
    username: 'prof_smith',
    email: 'smith@aums.edu',
    firstName: 'John',
    lastName: 'Smith',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['FACULTY'],
    permissions: ['students.read', 'faculty.read', 'courses.read', 'departments.read'],
  },
  student: {
    userId: 'demo-student-id',
    username: 'student_doe',
    email: 'doe@aums.edu',
    firstName: 'Jane',
    lastName: 'Doe',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['STUDENT'],
    permissions: ['students.read', 'courses.read', 'departments.read'],
  },
  parent: {
    userId: 'demo-parent-id',
    username: 'parent_doe',
    email: 'parent.doe@aums.edu',
    firstName: 'Robert',
    lastName: 'Doe',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['PARENT'],
    permissions: ['students.read', 'departments.read'],
  },
};
