import { CurrentUser } from '@/types/auth';

export const DEMO_USERS: Record<string, CurrentUser> = {
  super_admin: {
    userId: 'demo-super-admin-id',
    username: 'super_admin',
    email: 'admin@aums.com',
    firstName: 'Super',
    lastName: 'Admin',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['SUPER_ADMIN'],
    permissions: [
      'users.read',
      'roles.read',
      'permissions.read',
      'students.read',
      'faculty.read',
      'courses.read',
      'departments.read',
      'programs.read',
      'academic_years.read',
      'semesters.read',
      'course_offerings.read',
      'faculty_course_allocations.read',
      'student_course_registrations.read',
      'timetable.read',
      'attendance.read',
      'assignments.read',
      'assignment_submissions.read',
      'internal_assessments.read',
      'examinations.read',
    ],
  },
  faculty: {
    userId: 'demo-faculty-id',
    username: 'faculty_cse1',
    email: 'faculty.cse1@aums.edu',
    firstName: 'CSE Faculty',
    lastName: 'One',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['FACULTY'],
    permissions: ['students.read', 'faculty.read', 'courses.read', 'departments.read', 'programs.read', 'academic_years.read', 'semesters.read', 'course_offerings.read', 'faculty_course_allocations.read', 'student_course_registrations.read', 'timetable.read', 'attendance.read', 'assignments.read', 'assignment_submissions.read', 'internal_assessments.read', 'examinations.read'],
  },
  student: {
    userId: 'demo-student-id',
    username: 'student1',
    email: 'student1@aums.edu',
    firstName: 'Student',
    lastName: 'One',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['STUDENT'],
    permissions: ['students.read', 'courses.read', 'departments.read', 'programs.read', 'academic_years.read', 'semesters.read', 'course_offerings.read', 'faculty_course_allocations.read', 'student_course_registrations.read', 'timetable.read', 'attendance.read', 'assignments.read', 'assignment_submissions.read', 'internal_assessments.read', 'examinations.read'],
  },
  parent: {
    userId: 'demo-parent-id',
    username: 'parent1',
    email: 'parent1@aums.edu',
    firstName: 'Parent',
    lastName: 'One',
    status: 'active',
    isEmailVerified: true,
    isPhoneVerified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roles: ['PARENT'],
    permissions: ['students.read', 'departments.read', 'programs.read', 'academic_years.read', 'semesters.read', 'course_offerings.read', 'faculty_course_allocations.read', 'student_course_registrations.read', 'timetable.read', 'attendance.read', 'assignments.read', 'assignment_submissions.read', 'internal_assessments.read', 'examinations.read'],
  },
};

export const DEMO_CREDENTIALS = {
  superAdmin: {
    email: 'admin@aums.com',
    password: 'Admin@123',
  },
  institutionAdmin: {
    email: 'institution.admin@aums.edu',
    password: 'Admin@123',
  },
  dean: {
    email: 'dean.engineering@aums.edu',
    password: 'Admin@123',
  },
  hod: {
    email: 'hod.cse@aums.edu',
    password: 'Admin@123',
  },
  faculty: {
    email: 'faculty.cse1@aums.edu',
    password: 'Admin@123',
  },
  faculty2: {
    email: 'faculty.cse2@aums.edu',
    password: 'Admin@123',
  },
  student: {
    email: 'student1@aums.edu',
    password: 'Admin@123',
  },
  student2: {
    email: 'student2@aums.edu',
    password: 'Admin@123',
  },
  student3: {
    email: 'student3@aums.edu',
    password: 'Admin@123',
  },
  parent: {
    email: 'parent1@aums.edu',
    password: 'Admin@123',
  },
  parent2: {
    email: 'parent2@aums.edu',
    password: 'Admin@123',
  },
};
