-- ==========================================
-- AUMS IDENTITY DOMAIN
-- ==========================================

-- NOTE:
-- UUID v7 is generated by Go service layer.
-- No DEFAULT uuid generation in PostgreSQL.

-- ==========================================
-- ENUMS
-- ==========================================

CREATE TYPE user_status AS ENUM (
    'PENDING_VERIFICATION',
    'ACTIVE',
    'INACTIVE',
    'SUSPENDED',
    'LOCKED'
);

-- ==========================================
-- USERS
-- ==========================================

CREATE TABLE users (

    user_id UUID PRIMARY KEY,

    username VARCHAR(100),

    email CITEXT NOT NULL,

    phone_number VARCHAR(20),

    password_hash TEXT,

    first_name VARCHAR(100) NOT NULL,

    middle_name VARCHAR(100),

    last_name VARCHAR(100),

    profile_photo_url TEXT,

    status user_status NOT NULL DEFAULT 'PENDING_VERIFICATION',

    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,

    is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT uq_users_username
        UNIQUE (username)
);

-- ==========================================
-- ROLES
-- ==========================================

CREATE TABLE roles (

    role_id UUID PRIMARY KEY,

    role_code VARCHAR(50) NOT NULL,

    role_name VARCHAR(100) NOT NULL,

    description TEXT,

    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_role_code
        UNIQUE (role_code)
);

-- ==========================================
-- PERMISSIONS
-- ==========================================

CREATE TABLE permissions (

    permission_id UUID PRIMARY KEY,

    permission_code VARCHAR(150) NOT NULL,

    permission_name VARCHAR(255) NOT NULL,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_permission_code
        UNIQUE (permission_code)
);

-- ==========================================
-- USER ROLES
-- ==========================================

CREATE TABLE user_roles (

    user_role_id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    role_id UUID NOT NULL,

    assigned_by UUID,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_role
        UNIQUE (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_roles_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES users(user_id)
        ON DELETE SET NULL
);

-- ==========================================
-- ROLE PERMISSIONS
-- ==========================================

CREATE TABLE role_permissions (

    role_permission_id UUID PRIMARY KEY,

    role_id UUID NOT NULL,

    permission_id UUID NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_role_permission
        UNIQUE (role_id, permission_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions(permission_id)
        ON DELETE CASCADE
);

-- ==========================================
-- USER SESSIONS
-- ==========================================

CREATE TABLE user_sessions (

    session_id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    refresh_token_hash TEXT NOT NULL,

    device_name VARCHAR(255),

    ip_address VARCHAR(100),

    user_agent TEXT,

    expires_at TIMESTAMPTZ NOT NULL,

    revoked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX idx_users_status
ON users(status);

CREATE INDEX idx_users_deleted_at
ON users(deleted_at);

CREATE INDEX idx_user_roles_user
ON user_roles(user_id);

CREATE INDEX idx_user_roles_role
ON user_roles(role_id);

CREATE INDEX idx_role_permissions_role
ON role_permissions(role_id);

CREATE INDEX idx_role_permissions_permission
ON role_permissions(permission_id);

CREATE INDEX idx_user_sessions_user
ON user_sessions(user_id);

CREATE INDEX idx_user_sessions_expires
ON user_sessions(expires_at);