DROP TABLE IF EXISTS rooms CASCADE;

DROP TABLE IF EXISTS buildings CASCADE;

DROP TABLE IF EXISTS semesters CASCADE;

DROP TABLE IF EXISTS academic_years CASCADE;

DROP TABLE IF EXISTS programs CASCADE;

DROP TABLE IF EXISTS departments CASCADE;

DROP TABLE IF EXISTS schools CASCADE;

DROP TABLE IF EXISTS campuses CASCADE;

DROP TYPE IF EXISTS degree_type;