import { Student } from '../types';

export const DEMO_STUDENTS: Student[] = [
  {
    studentId: 'stud-001',
    rollNumber: 'CS2023001',
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane.doe@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-002',
    rollNumber: 'CS2023002',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-003',
    rollNumber: 'EC2022014',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@aums.edu',
    program: 'B.Tech',
    department: 'Electronics',
    semester: 6,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-004',
    rollNumber: 'ME2021008',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.j@aums.edu',
    program: 'B.Tech',
    department: 'Mechanical',
    semester: 8,
    status: 'graduated',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-005',
    rollNumber: 'CS2023005',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.w@aums.edu',
    program: 'M.Tech',
    department: 'Computer Science',
    semester: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-006',
    rollNumber: 'EC2023022',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.b@aums.edu',
    program: 'B.Tech',
    department: 'Electronics',
    semester: 4,
    status: 'suspended',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-007',
    rollNumber: 'CS2022045',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.d@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 6,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-008',
    rollNumber: 'ME2023015',
    firstName: 'James',
    lastName: 'Miller',
    email: 'james.m@aums.edu',
    program: 'B.Tech',
    department: 'Mechanical',
    semester: 2,
    status: 'inactive',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-009',
    rollNumber: 'CS2021089',
    firstName: 'Michael',
    lastName: 'Wilson',
    email: 'michael.w@aums.edu',
    program: 'Ph.D',
    department: 'Computer Science',
    semester: 6,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-010',
    rollNumber: 'EC2022081',
    firstName: 'Jessica',
    lastName: 'Moore',
    email: 'jessica.m@aums.edu',
    program: 'M.Tech',
    department: 'Electronics',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-011',
    rollNumber: 'CS2023011',
    firstName: 'Kevin',
    lastName: 'Taylor',
    email: 'kevin.t@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-012',
    rollNumber: 'ME2022029',
    firstName: 'Amanda',
    lastName: 'Anderson',
    email: 'amanda.a@aums.edu',
    program: 'B.Tech',
    department: 'Mechanical',
    semester: 6,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-013',
    rollNumber: 'CS2021004',
    firstName: 'Brian',
    lastName: 'Thomas',
    email: 'brian.t@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 8,
    status: 'graduated',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-014',
    rollNumber: 'EC2023099',
    firstName: 'Lisa',
    lastName: 'Jackson',
    email: 'lisa.j@aums.edu',
    program: 'B.Tech',
    department: 'Electronics',
    semester: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-015',
    rollNumber: 'CS2023015',
    firstName: 'Daniel',
    lastName: 'White',
    email: 'daniel.w@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 4,
    status: 'inactive',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-016',
    rollNumber: 'ME2022067',
    firstName: 'Rachel',
    lastName: 'Harris',
    email: 'rachel.h@aums.edu',
    program: 'M.Tech',
    department: 'Mechanical',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-017',
    rollNumber: 'CS2023017',
    firstName: 'Jason',
    lastName: 'Martin',
    email: 'jason.m@aums.edu',
    program: 'B.Tech',
    department: 'Computer Science',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-018',
    rollNumber: 'EC2021051',
    firstName: 'Patricia',
    lastName: 'Thompson',
    email: 'patricia.t@aums.edu',
    program: 'B.Tech',
    department: 'Electronics',
    semester: 8,
    status: 'graduated',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-019',
    rollNumber: 'CS2022091',
    firstName: 'Steven',
    lastName: 'Garcia',
    email: 'steven.g@aums.edu',
    program: 'Ph.D',
    department: 'Computer Science',
    semester: 4,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    studentId: 'stud-020',
    rollNumber: 'ME2023088',
    firstName: 'Nancy',
    lastName: 'Martinez',
    email: 'nancy.m@aums.edu',
    program: 'B.Tech',
    department: 'Mechanical',
    semester: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEPARTMENT_OPTIONS = [
  { label: 'Computer Science', value: 'Computer Science' },
  { label: 'Electronics', value: 'Electronics' },
  { label: 'Mechanical', value: 'Mechanical' },
];

export const PROGRAM_OPTIONS = [
  { label: 'B.Tech', value: 'B.Tech' },
  { label: 'M.Tech', value: 'M.Tech' },
  { label: 'Ph.D', value: 'Ph.D' },
];

export const STATUS_OPTIONS = [
  { label: 'Active', value: 'active' },
  { label: 'Inactive', value: 'inactive' },
  { label: 'Suspended', value: 'suspended' },
  { label: 'Graduated', value: 'graduated' },
];
